// This file was generated by Slater.app - app.js


(() => {
  if (window.Webflow && Webflow.env("editor")) return;
  document.documentElement.classList.remove('js-off');
  document.documentElement.classList.add('js-on');
  gsap.registerPlugin(ScrollTrigger, SplitText, Flip);

  // var options = {
  //   animate: true,
  //   patternWidth: 100,
  //   patternHeight: 100,
  //   grainOpacity: 0.,
  //   grainDensity: 1,
  //   grainWidth: 1,
  //   grainHeight: 1
  // };

  // grained("#grain", options);

  let scroll;
  let loaderPlayed = false;

  function initLenis() {
    if (window.Webflow && Webflow.env("editor")) return null;
    if (scroll) return scroll;

    scroll = new Lenis({
      duration: 1.05,
      smoothWheel: true,
      smoothTouch: false,
    });

    scroll.on("scroll", ScrollTrigger.update);

    gsap.ticker.add((t) => {
      scroll.raf(t * 1000);
    });
    gsap.ticker.lagSmoothing(0);

    ScrollTrigger.addEventListener("refresh", () => scroll.resize());

    window.__lenis = scroll;
    return scroll;
  }

  function scrollStop() {
    scroll?.stop?.();
    document.body.setAttribute("data-lenis-prevent", "true");
  }

  function scrollStart() {
    scroll?.start?.();
    document.body.removeAttribute("data-lenis-prevent");
  }

  function scrollResize() {
    scroll?.resize?.();
  }

  const state = {
    ctx: null,
    activeSplits: [],
    pageCleanup: null,
  };

  function initCustomCursor(scope = document, options = {}) {
    if (window.matchMedia("(hover: none)").matches) return;

    const {
      svgColor = null,
        textColor = null,
        text = null,
        hideOnClick = true,
    } = options;

    const cursor = document.querySelector("#cursor-svg");
    if (!cursor) return;

    const svgEl = cursor.querySelector(".cursor_svg_svg");
    const textEl = cursor.querySelector(".cursor_text");

    let targets = Array.from(scope.querySelectorAll("[data-custom-cursor]"));
    if (scope.hasAttribute && scope.hasAttribute("data-custom-cursor")) {
      targets.push(scope);
    }

    if (!targets.length) return;

    gsap.set(cursor, {
      position: "fixed",
      left: 0,
      top: 0,
      xPercent: -50,
      yPercent: -50,
      autoAlpha: 0,
    });

    let active = false;
    let lastX = 0;
    let lastY = 0;
    let rotateTween = null;

    const xTo = gsap.quickTo(cursor, "x", { duration: 0.18, ease: "power3.out" });
    const yTo = gsap.quickTo(cursor, "y", { duration: 0.18, ease: "power3.out" });

    const onPointerMove = (e) => {
      lastX = e.clientX;
      lastY = e.clientY;
      if (active) {
        xTo(lastX);
        yTo(lastY);
      }
    };

    const show = () => {
      active = true;

      if (svgColor && svgEl) {
        gsap.set(svgEl, { backgroundColor: svgColor });
      }
      if (textColor && textEl) {
        gsap.set(textEl, { color: textColor });
      }
      if (text && textEl) {
        textEl.textContent = text;
      }

      gsap.set(cursor, { x: lastX, y: lastY });
      gsap.killTweensOf(cursor, "autoAlpha");
      gsap.to(cursor, { autoAlpha: 1, duration: 0.24 });
    };

    const hide = () => {
      active = false;
      gsap.killTweensOf(cursor, "autoAlpha");
      gsap.to(cursor, { autoAlpha: 0, duration: 0.24 });

      if (rotateTween) {
        rotateTween.kill();
        rotateTween = null;
      }
    };

    window.addEventListener("pointermove", onPointerMove, { passive: true });
    targets.forEach((el) => {
      el.addEventListener("pointerenter", show);
      el.addEventListener("pointerleave", hide);
      if (hideOnClick) el.addEventListener("click", hide);
    });

    return () => {
      window.removeEventListener("pointermove", onPointerMove);
      targets.forEach((el) => {
        el.removeEventListener("pointerenter", show);
        el.removeEventListener("pointerleave", hide);
        if (hideOnClick) el.removeEventListener("click", hide);
      });
      gsap.killTweensOf(cursor);
      if (rotateTween) rotateTween.kill();
      gsap.set(cursor, { autoAlpha: 0 });
      if (svgEl) gsap.set(svgEl, { rotation: 0 });
    };
  }

  function initSplitText(scope, { track = true } = {}) {
    const targets = scope.querySelectorAll("[data-text-split]");
    targets.forEach((el) => {
      const isLines = el.getAttribute("data-lines") === "true";
      const split = new SplitText(el, {
        type: isLines ? "lines" : "lines,words,chars",
        mask: el.getAttribute("data-text-split") === "mask" ? "lines" : undefined,
        linesClass: "split-line",
        wordsClass: "split-word",
        charsClass: "split-char",
      })
      if (track) state.activeSplits.push(split);
      el._split = split;
    })
  }

  function cleanupSplitText() {
    state.activeSplits.forEach((s) => s?.revert?.());
    state.activeSplits = [];
  }

  function initCoverChildAnimations(section) {
    const animTypes = [
      {
        sel: "[data-animate-text-lg]",
        threshold: 0.8,
        build: (el) => addFlickerReveal(
          getFlickerTargets(el))
      },
      {
        sel: "[data-animate-text-lg1]",
        threshold: 0.8,
        build: (el) => addFlickerReveal1(
          getFlickerTargets(el))
      },
      { sel: "[data-animate-text-md]", threshold: 0.8, build: (el) => addTextMdAnimation(el) },
      {
        sel: "[data-animate-text-base]",
        threshold: 0.8,
        build: (el) => addTextBaseAnimation(
          el)
      },
      { sel: "[data-animate-cpt]", threshold: 0.8, build: (el) => addCptAnimation(el) },
      { sel: "[data-animate-img-reveal]", threshold: 0.8, build: (el) => addImageReveal(el) },
    ];
    const items = [];
    animTypes.forEach(({ sel, threshold, build }) => {
      section.querySelectorAll(sel).forEach((el) => {
        el.dataset.coverHandled = "1";
        const tl = gsap.timeline({ paused: true });
        tl.add(build(el));
        items.push({ el, tl, hasPlayed: false, threshold });
      });
    });

    function check() {
      items.forEach((item) => {
        if (item.hasPlayed) return;
        const rect = item.el.getBoundingClientRect();
        if (rect.top < window.innerHeight * item.threshold) {
          item.hasPlayed = true;
          item.tl.play();
        }
      });
    }
    return { check };
  }

  const MM_DESKTOP = "(min-width: 768px)";

  function setupCoverSection(section, { yPercent = -30, watchResize = true } = {}) {
    const mm = gsap.matchMedia();

    let ro;
    let debounceTimer;

    mm.add(MM_DESKTOP, () => {
      let lastHeight = 0;

      function updateMargin() {
        const h = section.offsetHeight;
        if (h === lastHeight) return;
        lastHeight = h;
        gsap.set(section, { marginBottom: -(h * (Math.abs(yPercent) / 100)) });
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(() => {
          ScrollTrigger.refresh(true);
          scroll?.resize?.();
        }, 100);
      }

      if (watchResize) {
        ro = new ResizeObserver(updateMargin);
        ro.observe(section);
      }
      updateMargin();

      const { check } = initCoverChildAnimations(section);

      gsap.fromTo(section, { yPercent: 0 }, {
        yPercent: yPercent,
        ease: "none",
        scrollTrigger: {
          trigger: section,
          start: "top bottom",
          end: "top top",
          scrub: true,
          invalidateOnRefresh: true,
          onUpdate: check,
        }
      });

      return () => {
        ro?.disconnect();
        clearTimeout(debounceTimer);
        gsap.set(section, { marginBottom: "", yPercent: 0 });
      };
    });

    return () => {
      mm.revert();
    };
  }

  function addFlickerReveal(targets, duration = 1) {
    const tl = gsap.timeline();
    tl.fromTo(targets, { autoAlpha: 1, yPercent: 160 }, {
      autoAlpha: 1,
      yPercent: 0,
      duration: 1,
      ease: "power4.out",
      stagger: { amount: duration },
    });
    return tl;
  }

  function addFlickerReveal1(targets) {
    const tl = gsap.timeline();
    tl.to(targets, {
        autoAlpha: 0,
        duration: 0.05,
        stagger: 0.03,
      })
      .to(targets, {
        autoAlpha: 1,
        duration: 0.1,
        stagger: 0.03,
      }, "0.1")
    return tl;
  }

  function addSvgSlideReveal(svgs) {
    const tl = gsap.timeline();
    tl.fromTo(svgs, { yPercent: 120 },
    {
      yPercent: 0,
      duration: 1,
      ease: "power4.out",
      stagger: 0.1,
      clearProps: "transform",
    });
    return tl;
  }

  function addHeroSvgSlideReveal(svgs) {
    const tl = gsap.timeline();
    tl.fromTo(svgs, { yPercent: 120 }, {
      yPercent: 0,
      duration: 1,
      ease: "power4.out",
      stagger: 0.4,
      clearProps: "transform",
    });
    return tl;
  }

  function getFlickerTargets(el) {
    const chars = el._split?.chars;
    if (chars && chars.length) return chars;

    const svg = el.matches("svg") ? el : el.querySelector("svg");
    if (svg) {
      const shapes = svg.querySelectorAll(
        "path, line, polyline, polygon, rect, circle, ellipse"
      );
      if (shapes.length) return shapes;
    }

    return [el];
  }

  function addCptAnimation(el) {
    const tl = gsap.timeline();
    if (!el?._split?.lines) return tl;
    tl.fromTo(
      el._split.lines, { autoAlpha: 1, yPercent: 120 },
      {
        autoAlpha: 1,
        yPercent: 0,
        duration: 1,
        ease: "power4.out",
        // stagger: { amount: 0.675 },
        // clearProps: "opacity,visibility",
      }
    );
    return tl;
  }

  function addTextMdAnimation(el) {
    const tl = gsap.timeline();
    if (!el?._split?.lines) return tl;
    tl.fromTo(
      el._split.lines, { yPercent: 120 },
      {
        yPercent: 0,
        duration: 1,
        ease: "power4.out",
        stagger: 0.1,
        clearProps: "transform",
      }
    );
    return tl;
  }

  function addTextBaseAnimation(el) {
    const tl = gsap.timeline();
    if (!el) return tl;
    tl.fromTo(
      el, { autoAlpha: 0, y: "0.5em" },
      {
        autoAlpha: 1,
        y: 0,
        duration: 1,
        ease: "power4.out",
        clearProps: "opacity,visibility,transform",
      }
    );
    return tl;
  }

  function addImageReveal(el) {
    const img = el.querySelector("img");
    const tl = gsap.timeline();
    tl.fromTo(el, { clipPath: "inset(0 0 100% 0 round 0.25em)" }, {
      clipPath: "inset(0 0 0% 0 round 0.25em)",
      duration: 1.25,
      ease: "power4.inOut"
    });
    tl.fromTo(img, { scale: 1.25, }, {
        scale: 1,
        duration: 1.75,
        ease: "power3.out"
      },
      "<"
    );
    return tl;
  }

  function addSvcImageReveal(el) {
    const img = el.querySelector("img");
    const tl = gsap.timeline();
    tl.fromTo(el, { clipPath: "inset(100% 0 0 0 round 0.25em)" },
    {
      clipPath: "inset(0% 0 0 0 round 0.25em)",
      duration: 1.25,
      ease: "power4.out"
    });
    tl.fromTo(img, { scale: 1.25, }, {
        scale: 1.05,
        duration: 1.75,
        ease: "power3.out"
      },
      "<"
    );
    return tl;
  }

  function addHeroImageReveal(el) {
    const img = el.querySelector("img");
    const tl = gsap.timeline();
    tl.fromTo(el, { scale: 0, transformOrigin: "center center" },
    {
      scale: 1,
      duration: 1,
      ease: "power2.out",
    });
    return tl;
  }

  function addHeroBtnReveal(el) {
    const tl = gsap.timeline();
    if (!el) return tl;
    const texts = el.querySelectorAll(".link_btn_text");
    const lines = Array.from(texts).flatMap(t => t._split?.lines || []);
    const btnLines = el.querySelectorAll(".link_btn_line");

    tl.fromTo(lines, { yPercent: 120 }, { yPercent: 0, duration: 1, ease: "power4.out" });
    tl.fromTo(btnLines, { clipPath: "inset(0 100% 0 0)" }, {
        clipPath: "inset(0 0% 0 0)",
        duration: 1,
        ease: "power4.inOut"
      },
      0.1
    );

    return tl;
  }

  function animateImageReveal(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-img-reveal]").forEach((el) => {
      if (el.dataset.coverHandled) return;
      const config = { trigger: el, start: "top 80%" };
      if (pinnedContainer && !pinnedContainer.contains(el)) {
        config.pinnedContainer = pinnedContainer;
      }
      const tl = gsap.timeline({ scrollTrigger: config });
      tl.add(addImageReveal(el));
    });
  }

  function animateImgParallax(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-img-parallax]").forEach((wrap) => {
      if (wrap.dataset.coverHandled) return;
      const img = wrap.querySelector("img");
      if (!img) return;

      const config = {
        trigger: wrap,
        start: "top bottom",
        end: "bottom top",
        scrub: true,
      };

      if (pinnedContainer && !pinnedContainer.contains(wrap)) {
        config.pinnedContainer = pinnedContainer;
      }

      gsap.set(img, { yPercent: -20 });

      gsap.to(img, {
        yPercent: 0,
        ease: "none",
        scrollTrigger: config,
      });
    });
  }

  function animateTextLg(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-text-lg]").forEach((el) => {
      if (el.dataset.coverHandled) return;
      const config = { trigger: el, start: "top 80%" };
      if (pinnedContainer && !pinnedContainer.contains(el)) {
        config.pinnedContainer = pinnedContainer;
      }
      const attrVal = el.getAttribute("data-animate-text-lg");
      const duration = attrVal ? parseFloat(attrVal) : 1;
      const tl = gsap.timeline({ scrollTrigger: config });
      tl.add(addFlickerReveal(getFlickerTargets(el), duration));
    });
  }

  function animateTextLg1(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-text-lg1]").forEach((el) => {
      if (el.dataset.coverHandled) return;
      const config = { trigger: el, start: "top 80%" };
      if (pinnedContainer && !pinnedContainer.contains(el)) {
        config.pinnedContainer = pinnedContainer;
      }
      const tl = gsap.timeline({ scrollTrigger: config });
      tl.add(addFlickerReveal1(getFlickerTargets(el)));
    });
  }

  function animateTextMd(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-text-md]").forEach((el) => {
      if (el.dataset.coverHandled) return;
      const config = { trigger: el, start: "top 80%" };
      if (pinnedContainer && !pinnedContainer.contains(el)) {
        config.pinnedContainer = pinnedContainer;
      }
      const tl = gsap.timeline({ scrollTrigger: config });
      tl.add(addTextMdAnimation(el));
    });
  }

  function animateTextBase(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-text-base]").forEach((el) => {
      if (el.dataset.coverHandled) return;
      const config = { trigger: el, start: "top 80%" };
      if (pinnedContainer && !pinnedContainer.contains(el)) {
        config.pinnedContainer = pinnedContainer;
      }
      const tl = gsap.timeline({ scrollTrigger: config });
      tl.add(addTextBaseAnimation(el));
    });
  }

  function animateCpt(scope, pinnedContainer = null) {
    scope.querySelectorAll("[data-animate-cpt]").forEach((el) => {
      if (el.dataset.coverHandled) return;
      const config = { trigger: el, start: "top 80%" };
      if (pinnedContainer && !pinnedContainer.contains(el)) {
        config.pinnedContainer = pinnedContainer;
      }
      const tl = gsap.timeline({ scrollTrigger: config });
      tl.add(addCptAnimation(el));
    });
  }

  function initCtaSection(container, pinnedContainer = null) {
    const cta = container.querySelector("[data-cta]");
    if (!cta) return;

    const headline = cta.querySelector("[data-cta-headline]");
    const text = cta.querySelector("[data-cta-text]");
    const btn = cta.querySelector("[data-cta-btn]");

    if (btn) {
      const btnTexts = btn.querySelectorAll(".link_btn_text");
      const lines = Array.from(btnTexts).flatMap(t => t._split?.lines || []);
      const btnLines = btn.querySelectorAll(".link_btn_line");
      if (lines.length) gsap.set(lines, { yPercent: 120 });
      if (btnLines.length) gsap.set(btnLines, { clipPath: "inset(0 100% 0 0)" });
    }

    const config = { trigger: cta, start: "top 80%" };
    if (pinnedContainer && !pinnedContainer.contains(cta)) {
      config.pinnedContainer = pinnedContainer;
    }

    const tl = gsap.timeline({ scrollTrigger: config });

    if (headline) tl.add(addTextMdAnimation(headline), 0);
    if (text) tl.add(addTextBaseAnimation(text), 0.35);
    if (btn) tl.add(addHeroBtnReveal(btn), 0.65);
  }

  function initFooterParallax(scope, pinnedContainer = null) {
    const footer = scope.querySelector(".footer_container");
    if (!footer) return;
    const lastSection = scope.querySelector("[data-last-section]");
    const overlay = footer.querySelector(".footer_overlay");

    const mm = gsap.matchMedia();

    mm.add(MM_DESKTOP, () => {
      const config = {
        trigger: lastSection,
        start: "bottom bottom",
        end: "bottom 30%",
        scrub: true,
      };
      if (pinnedContainer) {
        config.pinnedContainer = pinnedContainer;
      }
      gsap.set(footer, { yPercent: -10 });
      gsap.to(footer, {
        scrollTrigger: config,
        yPercent: 0,
        ease: "none",
      });
      gsap.fromTo(overlay, { autoAlpha: 0.375 }, {
        scrollTrigger: config,
        autoAlpha: 0,
        ease: "none",
      });

      return () => {
        gsap.set(footer, { clearProps: "transform" });
        gsap.set(overlay, { clearProps: "opacity,visibility" });
      };
    });
  }

  function initHoverAnimations(scope) {
    scope.querySelectorAll("[data-hover]").forEach((el) => {
      if (el.dataset.hoverInit === "1") return;
      el.dataset.hoverInit = "1";
      const type = el.dataset.hover;

      if (type === "flicker") {
        const targets = getFlickerTargets(el);
        if (!targets || !targets.length) return;
        const tl = gsap.timeline({ paused: true, defaults: { immediateRender: false } });
        tl.add(addFlickerReveal(targets));
        el.addEventListener("pointerenter", () => {
          if (!tl.isActive()) tl.restart();
        });
        return;
      }

      if (type === "flicker1") {
        const targets = getFlickerTargets(el);
        if (!targets || !targets.length) return;
        const tl = gsap.timeline({ paused: true, defaults: { immediateRender: false } });
        tl.add(addFlickerReveal1(targets));
        el.addEventListener("pointerenter", () => {
          if (!tl.isActive()) tl.restart();
        });
        return;
      }

      if (type === "slideup") {
        const { orig, clone } = setupSlideUpHover(el);

        el.addEventListener("pointerenter", () => {
          const h = el.offsetHeight;
          gsap.killTweensOf([orig, clone]);
          gsap.fromTo(orig, { scale: 1 }, {
            scale: 0.8,
            y: -h,
            duration: 0.45,
            ease: "power4.out",
            transformOrigin: "center center",
          });
          gsap.fromTo(clone, { scale: 0.8, }, {
            scale: 1,
            y: -h,
            duration: 0.45,
            ease: "power4.out",
            transformOrigin: "center center",
          });
        });
        el.addEventListener("pointerleave", () => {
          gsap.killTweensOf([orig, clone]);
          gsap.fromTo(orig, { scale: 0.8 }, {
            scale: 1,
            y: 0,
            duration: 0.3,
            ease: "power3.out",
            transformOrigin: "center center",
          });
          gsap.fromTo(clone, { scale: 1 }, {
            scale: 0.8,
            y: 0,
            duration: 0.3,
            ease: "power3.out",
            transformOrigin: "center center",
          });
        });
        return;
      }
    });
  }

  function initButtons(scope) {

    scope.querySelectorAll("[data-animate-btn]").forEach((el) => {
      const line1 = el.querySelector(".link_btn_line:not(.is-2)");
      const line2 = el.querySelector(".link_btn_line.is-2");

      el.addEventListener("mouseenter", () => {
        gsap.killTweensOf([line1, line2]);
        const tl = gsap.timeline();
        tl.to(line1, {
            clipPath: "inset(0 0 0 100%)",
            duration: 0.5,
            ease: "power3.inOut"
          })
          .fromTo(line2, {
            clipPath: "inset(0 100% 0 0",
          }, {
            clipPath: "inset(0 0% 0 0)",
            duration: 0.5,
            ease: "power3.inOut"
          }, "-=0.035")
      })

      el.addEventListener("mouseleave", () => {
        gsap.killTweensOf([line1, line2]);
        const tl = gsap.timeline();
        tl.to(line2, {
            clipPath: "inset(0 100% 0 0)",
            duration: 0.5,
            ease: "power3.inOut",
          })
          .to(line1, {
            clipPath: "inset(0 0 0 0%)",
            duration: 0.5,
            ease: "power3.inOut"
          }, "-=0.035")
      })

    })
  }

  function setupSlideUpHover(el) {
    const original = el.innerHTML;
    el.style.overflow = "hidden";
    el.style.position = "relative";
    el.innerHTML = `
    <span class="hover-slide-original" style="display:block;will-change:transform;">${original}</span>
    <span class="hover-slide-clone" style="display:block;position:absolute;top:100%;left:0;width:100%;will-change:transform;">${original}</span>
  `;

    const orig = el.querySelector(".hover-slide-original");
    const clone = el.querySelector(".hover-slide-clone");

    return { orig, clone };
  }

  function setupSvcArrow(svgEl) {
    const clone = svgEl.cloneNode(true);
    svgEl.parentNode.appendChild(clone);
    gsap.set(clone, { position: "absolute", x: "-120%", y: "120%", rotation: -45 });
    return { orig: svgEl, clone };
  }

  function initModals() {
    const overlay = document.querySelector(".modal_overlay");
    const modal = overlay?.querySelector(".modal_wrap");
    const bgOverlay = document.querySelector(".overlay");
    if (!overlay || !modal) return;

    gsap.set(overlay, { autoAlpha: 0, pointerEvents: "none" });
    gsap.set(modal, { yPercent: 4, autoAlpha: 0 });
    if (bgOverlay) gsap.set(bgOverlay, { autoAlpha: 0 });

    const open = () => {
      gsap.to(overlay, {
        autoAlpha: 1,
        pointerEvents: "all",
        duration: 0.375,
        ease: "power2.out"
      });
      gsap.to(modal, { yPercent: 0, autoAlpha: 1, duration: 0.5, ease: "power4.out" });
      if (bgOverlay) gsap.to(bgOverlay, {
        autoAlpha: 0.5,
        duration: 0.375,
        ease: "power2.out"
      });
    };

    const close = () => {
      gsap.to(overlay, {
        autoAlpha: 0,
        pointerEvents: "none",
        duration: 0.3,
        ease: "power2.in"
      });
      gsap.to(modal, { yPercent: 4, autoAlpha: 0, duration: 0.3, ease: "power2.in" });
      if (bgOverlay) gsap.to(bgOverlay, { autoAlpha: 0, duration: 0.3, ease: "power2.in" });
    };

    document.addEventListener("click", (e) => {
      if (e.target.closest("[data-modal-open]")) open();
    });

    overlay.addEventListener("click", (e) => {
      if (e.target === overlay) close();
    });

    overlay.querySelectorAll("[data-modal-close]").forEach(btn => {
      btn.addEventListener("click", close);
    });

    overlay.querySelectorAll("[data-modal-close]").forEach(btn => {
      btn.addEventListener("click", close);
    });
  }

  function initMobileMenu() {
    const menu = document.querySelector(".nav_menu");
    const toggleBtn = document.querySelector("[data-menu-toggle]");
    const links = Array.from(menu.querySelectorAll(".nav_menu_link_text"));
    if (!menu || !toggleBtn) return;

    let isOpen = false;
    let isAnimating = false;

    const textEl = toggleBtn.querySelector(".link_btn_text");
    const { orig, clone } = setupSlideUpHover(textEl);
    if (clone) clone.textContent = "Close";

    gsap.set(menu, { display: "none", clipPath: "inset(0 0 100% 0)" });

    const open = () => {
      if (isAnimating) return;
      isAnimating = true;

      scrollStop();
      document.documentElement.style.overflow = "hidden";

      links.forEach((link) => {
        gsap.set(link, { autoAlpha: 1 });
        const lines = link._split?.lines || [];
        if (lines.length) gsap.set(lines, { yPercent: 120 });
      });
      const h = toggleBtn.offsetHeight;
      isOpen = true;
      gsap.killTweensOf([orig, clone]);
      gsap.fromTo(orig, { y: 0, scale: 1 }, {
        y: -h,
        scale: 0.8,
        duration: 0.45,
        ease: "power4.out",
        transformOrigin: "center center"
      });
      gsap.fromTo(clone, { y: 0, scale: 0.8 }, {
        y: -h,
        scale: 1,
        duration: 0.45,
        ease: "power4.out",
        transformOrigin: "center center"
      });
      gsap.set(menu, { display: "flex" });
      gsap.to(menu, {
        clipPath: "inset(0 0 0% 0)",
        duration: 0.8,
        ease: "power4.inOut",
        onComplete: () => { isAnimating = false; },
      });

      links.forEach((link, i) => {
        const lines = link._split?.lines || [];
        if (!lines.length) return;
        gsap.set(lines, { yPercent: 120 });
        gsap.to(lines, {
          yPercent: 0,
          duration: 0.8,
          ease: "power4.out",
          delay: 0.3 + i * 0.08,
        });
      });
    };

    const close = () => {
      if (isAnimating) return;
      isAnimating = true;
      const h = toggleBtn.offsetHeight;
      isOpen = false;
      gsap.killTweensOf([orig, clone]);
      gsap.fromTo(orig, { y: -h, scale: 0.8 }, {
        y: 0,
        scale: 1,
        duration: 0.3,
        ease: "power3.out",
        transformOrigin: "center center"
      });
      gsap.fromTo(clone, { y: -h, scale: 1 }, {
        y: 0,
        scale: 0.8,
        duration: 0.3,
        ease: "power3.out",
        transformOrigin: "center center"
      });
      gsap.to(menu, {
        clipPath: "inset(0 0 100% 0)",
        duration: 0.5,
        ease: "power4.inOut",
        onComplete: () => {
          gsap.set(menu, { display: "none" });
          isAnimating = false;
        },
      });
      scrollStart();
      document.documentElement.style.overflow = "";
    };

    const closeInstant = () => {
      if (!isOpen) return;
      gsap.to(links, { autoAlpha: 0, duration: 0.3, ease: "power2.in" });
      gsap.set(orig, { y: 0, scale: 1 });
      gsap.set(clone, { y: 0, scale: 0.8 });
      scrollStart();
      document.documentElement.style.overflow = "";
    };

    window.__closeMobileMenu = () => {
      if (!isOpen) return;
      isOpen = false;
      isAnimating = false;
      gsap.killTweensOf([orig, clone]);
      gsap.set(orig, { y: 0, scale: 1 });
      gsap.set(clone, { y: 0, scale: 0.8 });
      gsap.set(menu, { display: "none", clipPath: "inset(0 0 100% 0)" });
      scrollStart();
      document.documentElement.style.overflow = "";
    };

    window.addEventListener("resize", () => {
      if (window.innerWidth >= 768 && isOpen) close();
    });

    toggleBtn.addEventListener("click", () => isOpen ? close() : open());

    menu.querySelectorAll("[data-nav-menu-link]").forEach(link => {
      link.addEventListener("click", closeInstant);
    });
  }

  function initPersistentUI() {
    const nav = document.querySelector("[data-navbar]");
    if (nav) {
      initSplitText(nav, { track: false });
      initHoverAnimations(nav);
      initButtons(nav);
    }

    const modal = document.querySelector(".modal_overlay");
    if (modal) {
      initSplitText(modal, { track: false });
      initHoverAnimations(modal);
      initButtons(modal);
    }

    const menu = document.querySelector("[data-nav-menu]");
    if (menu) {
      initSplitText(menu, { track: false });
      initHoverAnimations(menu);
      initButtons(menu);
    }

    initModals();
    initMobileMenu();
  }

  function setNavCurrent(namespace) {
    const nav = document.querySelector("[data-navbar]");
    if (!nav) return;

    const links = nav.querySelectorAll("[data-nav-link]");
    links.forEach((a) => {
      const isCurrent = a.dataset.navLink === namespace;
      a.classList.toggle("is-current", isCurrent);

      if (isCurrent) a.setAttribute("aria-current", "page");
      else a.removeAttribute("aria-current");
    });
  }

  function setNavTransitionMode(isOn) {
    const nav = document.querySelector("[data-navbar]");
    if (!nav) return;
    nav.classList.toggle("is-transitioning", isOn);
  }

  function initCommon(container) {
    initSplitText(container, { track: true });
    initButtons(container);
    initHoverAnimations(container);
  }

  function initScrollAnimations(container, pinnedContainer = null) {
    animateCpt(container, pinnedContainer);
    animateImageReveal(container, pinnedContainer);
    animateImgParallax(container, pinnedContainer);
    animateTextLg(container, pinnedContainer);
    animateTextLg1(container, pinnedContainer);
    animateTextMd(container, pinnedContainer);
    animateTextBase(container, pinnedContainer);
    initCtaSection(container, pinnedContainer);
    initFooterParallax(container, pinnedContainer);
  }

  function playHeroIntro(container) {
    const hero = container.querySelector("[data-hero]");
    if (!hero) return;
    const namespace = container.dataset.barbaNamespace;
    const svgs = Array.from(hero.querySelectorAll("[data-hero-svg]"));
    const mdEl = hero.querySelector("[data-hero-text-md]");
    const cptEls = hero.querySelectorAll("[data-hero-cpt]");
    const texts = hero.querySelectorAll("[data-hero-text]");
    const imgs = hero.querySelectorAll("[data-hero-img]");
    const btn = hero.querySelector("[data-hero-btn]");

    const tl = gsap.timeline();

    if (namespace === "home") {
      tl.add(addHeroSvgSlideReveal(svgs));
      if (btn) tl.add(addHeroBtnReveal(btn), 1.1);
      imgs.forEach((img) => tl.add(addHeroImageReveal(img), 1.2));
      // Custom EAD slide-down + LSM typewriter
      var heroEad = hero.querySelector('#hero-ead');
      var heroLsm = hero.querySelector('#hero-lsm');
      if (heroEad) {
        tl.to(heroEad, { opacity: 1, x: 0, y: 0, duration: 1.4, ease: 'power4.out' }, 0.8);
      }
      if (heroLsm) {
        var _letters = ['L','S','M','.'];
        _letters.forEach(function(_ch, _i) {
          tl.call(function(){ heroLsm.textContent += _ch; }, null, 2.0 + _i * 0.22);
        });
        tl.to(heroLsm, { borderRightColor: 'transparent', repeat: 5, yoyo: true, duration: 0.3, ease: 'steps(1)' }, 3.0);
        tl.set(heroLsm, { borderRight: 'none', paddingRight: '0' }, 4.6);
      }
      tl.add(addTextMdAnimation(mdEl), 1.2);
      cptEls.forEach((el) => tl.add(addCptAnimation(el), 1.2));
      texts.forEach((text) => tl.add(addTextBaseAnimation(text), 1.2));
    } else {
      tl.add(addSvgSlideReveal(svgs));
      if (namespace === "services") { imgs.forEach((img) => tl.add(addSvcImageReveal(img), 0)); }
      else { imgs.forEach((img) => tl.add(addImageReveal(img), 0)); }
      tl.add(addTextMdAnimation(mdEl), 0.375);
      cptEls.forEach((el) => tl.add(addCptAnimation(el), 0.5));
      texts.forEach((text) => tl.add(addTextBaseAnimation(text), 0.5));
      if (namespace === "404") tl.add(addHeroBtnReveal(btn), 0.5);
    }

    return tl;
  }

  //HOME Functions

  function initHomeHero(container) {
    const hero = container.querySelector("[data-hero]");
    if (!hero) return;
    const wrap = hero.querySelector("[data-hero-img]");
    if (!wrap) return;
    const imgs = Array.from(wrap.querySelectorAll("img"));
    if (!imgs.length) return;

    let currentIndex = 0;
    let zCounter = 1;

    gsap.set(imgs, { transformOrigin: "center center" });
    gsap.set(imgs[0], { zIndex: 1 });

    imgs.forEach((img) => {
      img.setAttribute("draggable", "false");
      img.style.userSelect = "none";
      img.style.webkitUserSelect = "none";
    });

    let maxTravel = 0;

    function recalculate() {
      const rect = hero.getBoundingClientRect();
      if (!rect.width) return;
      const paddingPx = parseFloat(getComputedStyle(hero).fontSize) * 1.25;
      maxTravel = Math.max(40, (rect.width - wrap.offsetWidth) / 2 - paddingPx); // ← min 40px travel
      const currentX = gsap.getProperty(wrap, "x");
      const clamped = Math.max(-maxTravel, Math.min(maxTravel, currentX));
      gsap.set(wrap, { x: clamped });
    }
    recalculate();

    const ro = new ResizeObserver(recalculate);
    ro.observe(hero);

    const onMouseMove = (e) => {
      const rect = hero.getBoundingClientRect();
      const centerX = rect.left + rect.width / 2;
      const relX = e.clientX - centerX;
      const normalized = relX / (rect.width / 2);
      const x = Math.max(-maxTravel, Math.min(maxTravel, normalized * maxTravel));
      gsap.to(wrap, { x, duration: 0.8, ease: "power3.out" });
    };

    const onClick = () => {
      const nextIndex = (currentIndex + 1) % imgs.length;
      zCounter++;
      gsap.set(imgs[nextIndex], { zIndex: zCounter });
      gsap.fromTo(imgs[nextIndex], { scale: 0, autoAlpha: 1 }, {
        scale: 1.01,
        autoAlpha: 1,
        duration: 0.5,
        ease: "power3.out"
      });
      currentIndex = nextIndex;
    };

    hero.addEventListener("mousemove", onMouseMove, { passive: true });
    wrap.addEventListener("click", onClick);

    return () => {
      hero.removeEventListener("mousemove", onMouseMove);
      wrap.removeEventListener("click", onClick);
      ro.disconnect();
      gsap.to(wrap, { x: 0, duration: 0.5 });
    };
  }

  function initHomeIntro(container) {
    const svgEl = container.querySelector(".intro_main_svg");
    const introContent = container.querySelector(".intro_main_text_wrap")
    gsap.to(svgEl, {
      ease: "none",
      scrollTrigger: {
        trigger: introContent,
        start: "top 100%",
        end: "100% 0%",
        scrub: true,
      },
      yPercent: -35,
    });
  }

  function initHomeCover(container) {
    const introSection = container.querySelector(".intro_container");
    const heroOverlay = container.querySelector(".hero_overlay");
    gsap.set(introSection, { position: "relative", zIndex: 2 });

    const cleanupCover = setupCoverSection(introSection);

    gsap.fromTo(heroOverlay, { autoAlpha: 0 },
    {
      autoAlpha: 1,
      ease: "none",
      immediateRender: false,
      scrollTrigger: {
        trigger: introSection,
        start: "top bottom",
        end: "top top",
        scrub: true,
        invalidateOnRefresh: true,
      }
    });

    return cleanupCover;
  }

  function initWorkImageHover(container) {
    const wrap = container.querySelector(".work_main_img_wrapper");
    if (!wrap) return null;

    const items = Array.from(wrap.querySelectorAll("[data-work-item]"));
    if (items.length < 2) return null;

    const imgs = items.map((el) => el.querySelector("img")).filter(Boolean);
    const overlays = items.map((el) => el.querySelector(".work_img_overlay")).filter(Boolean);

    if (overlays.length !== items.length) return null;

    const onEnter = (e) => {
      const activeIndex = items.indexOf(e.currentTarget);
      items.forEach((_, i) => {
        const isActive = i === activeIndex;
        gsap.to(overlays[i], { opacity: isActive ? 0 : 0.75, duration: 0.25 });
        gsap.to(imgs[i], {
          scale: isActive ? 1.1 : 1.01,
          duration: 0.25,
          ease: "power2.out"
        });
      });
    };

    const onLeave = () => {
      gsap.to(overlays, { opacity: 0, duration: 0.25 });
      gsap.to(imgs, { scale: 1, duration: 0.25 });
    };

    items.forEach((item) => {
      item.addEventListener("pointerenter", onEnter);
      item.addEventListener("pointerleave", onLeave);
    });
  }

  function initHomeWork(container) {
    const workMain = container.querySelector(".work_main_wrap");
    if (!workMain) return;

    const cleanupCursor = initCustomCursor(workMain, {
      svgColor: "var(--color-white)",
      textColor: "var(--color-black)",
      text: "View Project"
    });

    const img2 = workMain.querySelector(".work_collection_list_wrap.is-2");
    const img3 = workMain.querySelector(".work_collection_list_wrap.is-3");
    if (!img2 || !img3) return;

    const titleEl = workMain.querySelector("[data-work-title]");
    const numberEl = workMain.querySelector("[data-work-number]");
    const descEl = workMain.querySelector("[data-work-desc]");
    const yearEl = workMain.querySelector("[data-work-year]");
    const serviceEls = Array.from(workMain.querySelectorAll(".work_main_bottom_list_cpt"));

    const bgs = [
      workMain.querySelector(".work_main_bg.is-1"),
      workMain.querySelector(".work_main_bg.is-2"),
      workMain.querySelector(".work_main_bg.is-3"),
    ].filter(Boolean);

    const cases = [
    {
      title: "LUMEN",
      number: "01",
      desc: "Identity communication for a contemporary gallery defined by what it doesn't show.",
      year: "2026",
      services: ["Brand Identity", "Spatial Design", "Art Direction"],
    },
    {
      title: "C. Ground",
      number: "02",
      desc: "A real estate developer building with weight, permanence, and the city in mind.",
      year: "2026",
      services: ["Brand Identity", "Art Direction", "Digital Design"],
    },
    {
      title: "Modular",
      number: "03",
      desc: "A creative studio built to move between disciplines without losing form.",
      year: "2026",
      services: ["Brand Identity", "Art Direction", "Digital Design"],
    }, ];

    const CLOSED = "inset(0 50% 0 50%)";
    const OPEN = "inset(0 0% 0 0%)";

    gsap.set(bgs[0], { zIndex: 0, clipPath: OPEN });
    gsap.set(bgs[1], { zIndex: 1, clipPath: CLOSED });
    gsap.set(bgs[2], { zIndex: 2, clipPath: CLOSED });
    gsap.set([img2, img3], { clipPath: "inset(100% 0 0 0)", zIndex: 2, scale: 1.01 });

    let currentIndex = 0;
    let animating = false;

    function renderCase(i) {
      const c = cases[i];
      if (!c) return;
      if (titleEl) titleEl.textContent = c.title;
      if (numberEl) numberEl.textContent = c.number;
      if (descEl) descEl.textContent = c.desc;
      if (yearEl) yearEl.textContent = c.year;
      serviceEls.forEach((el, i) => {
        if (el) el.textContent = c.services[i] ?? "";
      });
    }

    function splitEl(el) {
      if (!el) return;
      if (el._split) {
        el._split.revert();
        el._split = null;
      }
      const split = new SplitText(el, {
        type: "lines",
        mask: "lines",
        linesClass: "split-line",
      });
      el._split = split;
      state.activeSplits.push(split);
    }

    function revertEl(el) {
      if (!el?._split) return;
      el._split.revert();
      el._split = null;
    }

    function revealBg(i) {
      const bg = bgs[i];
      if (!bg) return;
      gsap.killTweensOf(bg);
      gsap.fromTo(bg, { clipPath: CLOSED }, {
        clipPath: OPEN,
        duration: 0.75,
        ease: "power3.out"
      });
    }

    function hideBg(i) {
      const bg = bgs[i];
      if (!bg) return;
      gsap.killTweensOf(bg);
      gsap.to(bg, { clipPath: CLOSED, duration: 0.75, ease: "power3.inOut" });
    }

    function setBgsForIndex(targetIndex, prevIndex) {
      const goingForward = targetIndex > prevIndex;

      if (goingForward) {
        for (let i = prevIndex + 1; i <= targetIndex; i++) {
          revealBg(i);
        }
      } else {
        for (let i = prevIndex; i > targetIndex; i--) {
          hideBg(i);
        }
      }
    }

    let pendingUpdate = null;

    function updateCaseTo(targetIndex) {
      if (targetIndex === currentIndex) return;

      if (pendingUpdate) {
        pendingUpdate.kill();
        pendingUpdate = null;
      }

      const prevIndex = currentIndex;
      currentIndex = targetIndex;

      setBgsForIndex(targetIndex, prevIndex);

      const nodes = [descEl, yearEl, ...serviceEls].filter(Boolean);
      gsap.to(nodes, { autoAlpha: 0, duration: 0.25 });

      const oldLines = [
        ...(titleEl?._split?.lines || []),
        ...(numberEl?._split?.lines || []),
      ];
      if (oldLines.length) {
        gsap.killTweensOf(oldLines);
        gsap.to(oldLines, {
          yPercent: -120,
          duration: 0.7,
          ease: "power4.out",
        });
      }

      pendingUpdate = gsap.delayedCall(0.35, () => {
        revertEl(titleEl);
        revertEl(numberEl);
        renderCase(targetIndex);
        splitEl(titleEl);
        splitEl(numberEl);

        const newLines = [
          ...(titleEl?._split?.lines || []),
          ...(numberEl?._split?.lines || []),
        ];

        gsap.set(newLines, { yPercent: 120 });
        gsap.to(nodes, { autoAlpha: 1, duration: 0.25 });
        gsap.to(newLines, {
          yPercent: 0,
          duration: 0.7,
          ease: "power4.out",
        });
        pendingUpdate = null;
      });
    }

    let lastProgress = 0;

    function getTargetIndex(progress) {
      const goingDown = progress > lastProgress;

      const crossed = (threshold) => {
        return goingDown ?
          (lastProgress < threshold && progress >= threshold) :
          (lastProgress >= threshold && progress < threshold);
      };

      let newIndex = currentIndex;

      if (goingDown) {
        if (crossed(0.5)) newIndex = 1;
        if (crossed(0.999)) newIndex = 2;
      } else {
        if (crossed(0.5)) newIndex = 1;
        if (crossed(0.001)) newIndex = 0;
      }

      lastProgress = progress;

      return newIndex;
    }

    renderCase(0);
    splitEl(titleEl);
    splitEl(numberEl);

    const scrollTl = gsap.timeline({
      scrollTrigger: {
        trigger: workMain,
        start: "top top",
        end: "+=200%",
        scrub: true,
        pin: true,
        pinSpacing: true,
        invalidateOnRefresh: true,
        onUpdate(self) {
          const targetIndex = getTargetIndex(self.progress);
          if (targetIndex !== currentIndex) {
            updateCaseTo(targetIndex);
          }
        },
      },
    });

    scrollTl.to(img2, { clipPath: "inset(0% 0 0 0)", duration: 1, ease: "none" });
    scrollTl.to(img3, { clipPath: "inset(0% 0 0 0)", duration: 1, ease: "none" });

    return cleanupCursor;
  }

  function initHomeServices(container) {
    const wrap = container.querySelector(".svc_main_wrap");
    if (!wrap) return;
    const items = Array.from(wrap.querySelectorAll(".svc_main_item"));
    if (!items.length) return;

    const cleanupCursor = initCustomCursor(wrap, {
      svgColor: "var(--color-white)",
      textColor: "var(--color-black)",
      text: "Learn More"
    });

    items.forEach((item) => {
      item.style.cursor = "pointer";
      const itemWrap = item.querySelector(".svc_main_item_content_wrap");
      const overlay = item.querySelector(".svc_hover_overlay");
      const svg = item.querySelector("[data-svc-svg]");
      const heading = item.querySelector(".svc_main_item_name_text");

      const { orig: svgOrig, clone: svgClone } = setupSvcArrow(svg);
      gsap.set(svgOrig, { x: 0, y: 0, rotation: 0 });
      gsap.set(svgClone, { x: "-120%", y: "120%", rotation: -45 });

      if (overlay) gsap.set(overlay, {
        scaleY: 0,
        transformOrigin: "bottom center",
        force3D: true
      });

      item.addEventListener("mouseenter", () => {
        gsap.killTweensOf([overlay, itemWrap, svg, heading, svgOrig, svgClone]);
        if (overlay) gsap.to(overlay, {
          scaleY: 1,
          duration: 0.75,
          ease: "power4.out",
        });
        if (itemWrap) gsap.to(itemWrap, { color: "var(--color-white)", duration: 0.375 });
        gsap.to(svgOrig, {
          x: "120%",
          duration: 0.5,
          ease: "power4.out"
        });
        gsap.to(svgClone, {
          x: "0%",
          y: "0%",
          duration: 0.5,
          ease: "power4.out",
          delay: 0.2
        });
        if (heading) gsap.to(heading, {
          scale: 0.98,
          duration: 1,
          ease: "power4.out"
        });
      });

      item.addEventListener("mouseleave", () => {
        gsap.killTweensOf([overlay, itemWrap, svg, heading, svgOrig, svgClone]);
        if (overlay) gsap.to(overlay, {
          scaleY: 0,
          duration: 0.75,
          ease: "power4.out",
        });
        if (itemWrap) gsap.to(itemWrap, { color: "var(--color-black)", duration: 0.375 });
        gsap.to(svgOrig, { x: 0, duration: 0.75, ease: "power4.out", delay: 0.2 });
        gsap.to(svgClone, {
          x: "-120%",
          y: "120%",
          duration: 0.75,
          ease: "power4.out",
        });
        if (heading) gsap.to(heading, { scale: 1, duration: 0.375, ease: "power4.out" });
      });
    });

    return () => cleanupCursor?.();
  }

  function initHomeAbout(container) {
    const topWrap = container.querySelector(".about_top_wrap");
    const mainWrap = container.querySelector(".about_main_wrap");
    const imgEl = mainWrap.querySelector(".about_main_img_wrap");
    const svgEl = topWrap.querySelector(".about_top_svg");

    gsap.from(svgEl, {
      scrollTrigger: {
        trigger: svgEl,
        start: "top 60%",
      },
      yPercent: -120,
      ease: "power4.out",
      duration: 1,
      delay: 0.5,
    });

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: mainWrap,
        start: "top 80%",
      },
    });

    tl.add(addImageReveal(imgEl));
  }

  function initServicesMarquee(container) {
    const marqueeWrap = container.querySelector(".svc_intro_marquee");
    if (!marqueeWrap) return;
    const marqueeItem = marqueeWrap.querySelector(".svc_intro_marquee_item");
    if (!marqueeItem) return;
    const clone = marqueeItem.cloneNode(true);
    marqueeWrap.appendChild(clone);

    let tl;

    function createAnimation() {
      if (tl) tl.kill();
      const itemWidth = marqueeItem.offsetWidth;
      const duration = 25;
      gsap.set([marqueeItem, clone], { x: 0 });
      tl = gsap.timeline({ repeat: -1 });
      tl.to([marqueeItem, clone], {
        x: -itemWidth,
        duration: duration,
        ease: "none",
      });
    }
    createAnimation();

    const resizeObserver = new ResizeObserver(() => {
      createAnimation();
    });
    resizeObserver.observe(marqueeWrap);

    return () => {
      resizeObserver.disconnect();
    };
  }

  function initServicesSvc(container) {
    const mainWrap = container.querySelector(".svc_svc_main_wrap");
    if (!mainWrap) return;
    const items = Array.from(mainWrap.querySelectorAll(".svc_svc_item_wrap"));
    if (items.length < 2) return;

    const mm = gsap.matchMedia();

    mm.add(MM_DESKTOP, () => {
      items.forEach((item, i) => {
        gsap.set(item, { zIndex: i + 1, yPercent: i === 0 ? 0 : 100 });
      });

      const pauseDuration = 0.25;
      const slideDuration = 1;
      const totalDuration = (items.length - 1) * (slideDuration + pauseDuration) +
        pauseDuration;

      const scrollTl = gsap.timeline({
        scrollTrigger: {
          trigger: mainWrap,
          start: "top top",
          end: `+=${(totalDuration / (items.length - 1)) * 100 * (items.length - 1)}%`,
          scrub: true,
          pin: true,
          pinSpacing: true,
          invalidateOnRefresh: true,
        },
      });

      scrollTl.to({}, { duration: pauseDuration });

      for (let i = 1; i < items.length; i++) {
        const overlay = items[i - 1].querySelector(".svc_item_overlay");
        const prevItem = items[i - 1].querySelector(".svc_svc_item");
        const prevOverlay = i > 1 ? items[i - 2].querySelector(".svc_item_overlay") : null;

        if (prevOverlay) {
          scrollTl.to(prevOverlay, { autoAlpha: 0, duration: pauseDuration, ease: "none" },
            "<");
        }
        scrollTl.to(prevItem, {
          scale: 0.87,
          rotation: 3,
          transformOrigin: "center bottom",
          duration: slideDuration,
          ease: "none",
        });
        scrollTl.to(items[i], { yPercent: 0, duration: slideDuration, ease: "none" }, "<");
        scrollTl.to(overlay, { autoAlpha: 0.5, duration: slideDuration, ease: "none" }, "<");

        if (i < items.length - 1) scrollTl.to({}, { duration: pauseDuration });
      }

      return () => {
        items.forEach((item) => gsap.set(item, { clearProps: "transform,zIndex" }));
      };
    });
  }

  function initServicesTestimonials(container) {
    const wrap = container.querySelector(".svc_tst_items_wrap");
    if (!wrap) return;

    const cleanupCursor = initCustomCursor(wrap, {
      svgColor: "var(--color-white)",
      textColor: "var(--color-black)",
      text: "Drag",
      hideOnClick: false,
    });

    gsap.registerPlugin(Draggable, InertiaPlugin);

    const draggable = Draggable.create(wrap, {
      type: "x",
      edgeResistance: 0.65,
      throwProps: true,
      bounds: container.querySelector(".svc_tst_bottom_wrap"), // or wrap.parentElement
      cursor: "auto",
      activeCursor: "auto",
      zIndexBoost: false,
      onDrag: function () {
        const maxDrag = -(wrap.scrollWidth - wrap.parentElement.offsetWidth);
        if (this.x < maxDrag) this.x = maxDrag;
        if (this.x > 0) this.x = 0;
      }
    })[0];

    return () => {
      draggable.kill();
      cleanupCursor?.();
    };
  }

  function initServicesCover(container) {
    const svcSection = container.querySelector(".svc_svc_container");
    if (!svcSection) return;

    const mm = gsap.matchMedia();

    mm.add(MM_DESKTOP, () => {
      const lastSection = container.querySelector("[data-svc-last-section]");
      const overlay = svcSection.querySelector(".svc_overlay");
      const inner = svcSection.querySelector(".svc_svc_main_wrap");

      gsap.set(svcSection, { position: "relative", zIndex: 1 });

      gsap.fromTo(inner, { yPercent: -30 }, {
        yPercent: 0,
        ease: "none",
        immediateRender: false,
        scrollTrigger: {
          trigger: lastSection,
          start: "bottom bottom",
          end: "bottom top",
          scrub: true,
          invalidateOnRefresh: true,
        }
      });

      if (overlay) {
        gsap.fromTo(overlay, { autoAlpha: 0.6 }, {
          autoAlpha: 0,
          ease: "none",
          immediateRender: false,
          scrollTrigger: {
            trigger: lastSection,
            start: "bottom bottom",
            end: "bottom top",
            scrub: true,
            invalidateOnRefresh: true,
          }
        });
      }

      return () => {
        gsap.set(svcSection, { clearProps: "position,zIndex" });
        gsap.set(inner, { clearProps: "transform" });
        if (overlay) gsap.set(overlay, { clearProps: "opacity,visibility" });
      };
    });
  }

  function initAboutCover(container) {
    const valuesSection = container.querySelector(".abt_values_container");
    // const teamSection = container.querySelector(".abt_team_container");
    gsap.set(valuesSection, { position: "relative", zIndex: 2 });

    const cleanupValues = setupCoverSection(valuesSection);
    // const cleanupTeam = setupCoverSection(teamSection);

    return () => {
      cleanupValues();
      // cleanupTeam();
    };
  }

  function initAboutDropdown(container) {
    const items = container.querySelectorAll(".abt_values_item_right_wrap");
    let activeItem = null;
    let activeIndex = null;

    items.forEach((item, index) => {
      const wrap = item.querySelector(".abt_values_expanded_outer_wrap");

      item.addEventListener("mouseenter", () => {
        const text = item.querySelector(".abt_values_item_name");
        gsap.to(text, {
          marginLeft: "0.5em",
          duration: 0.25,
          ease: "power2.out",
        })
      })

      item.addEventListener("mouseleave", () => {
        const text = item.querySelector(".abt_values_item_name");
        gsap.to(text, {
          marginLeft: "0em",
          duration: 0.25,
          ease: "power2.out",
        })
      })

      item.addEventListener("click", () => {
        const arrow = container.querySelector(`[data-abt-arrow="${index}"]`);
        const text = item.querySelector(".abt_values_item_name");
        const svgEl = item.querySelector("[data-abt-svg]");

        if (activeItem) {
          const activeArrow = container.querySelector(
            `[data-abt-arrow="${activeIndex}"]`);
          const activeWrap = activeItem.querySelector(".abt_values_expanded_outer_wrap");
          const activeSvg = activeItem.querySelector("[data-abt-svg]")
          gsap.to(activeWrap, {
            height: 0,
            duration: 0.6,
            ease: "power3.inOut"
          });
          gsap.to(activeSvg, {
            autoAlpha: 1,
            duration: 0.125,
          });
          gsap.fromTo(activeArrow, {
            xPercent: 0,
          }, {
            xPercent: 120,
            duration: 0.6,
            ease: "power3.inOut",
          })
        }

        if (activeItem === item) {
          activeItem = null;
          activeIndex = null;
        } else {
          gsap.fromTo(wrap, { height: 0 }, {
            height: "auto",
            duration: 0.6,
            ease: "power3.inOut"
          });
          gsap.to(svgEl, {
            autoAlpha: 0,
            duration: 0.125,
          });
          gsap.fromTo(arrow, {
            autoAlpha: 1,
            xPercent: -120,
          }, {
            duration: 0.6,
            xPercent: 0,
            ease: "power3.inOut",
          });
          activeItem = item;
          activeIndex = index;
        }

        gsap.to(text, {
          marginLeft: "0em",
          duration: 0.25,
          ease: "power2.out",
        });

        ScrollTrigger.refresh(true);
        scroll?.resize?.();
      });
    });
  }

  function initAboutTeam(container) {
    const heading1 = container.querySelector(".abt_team_text");
    const heading2 = container.querySelector(".abt_team_cnt");

    const allChars = [
      ...(heading1?._split?.chars || []),
      ...(heading2?._split?.chars || []),
    ];

    if (allChars.length) {
      gsap.set(allChars, { yPercent: 160 });
      const tl = gsap.timeline({
        scrollTrigger: { trigger: heading1, start: "top 80%" },
      });
      tl.add(addFlickerReveal(allChars, 0.75));
    }

    const allMembers = Array.from(container.querySelectorAll(".abt_team_main_member"));
    const allImgs = allMembers.map(m => m.querySelector(".abt_team_main_member_photo")).filter(
      Boolean);
    const allWraps = allMembers.map(m => m.querySelector(".abt_team_main_member_wrap")).filter(
      Boolean);

    gsap.set(allWraps, { clipPath: "inset(100% 0 0% 0 round 0.25em)", scale: 1.2 });
    gsap.fromTo(allWraps, { clipPath: "inset(100% 0 0% 0 round 0.25em)", scale: 1.2 },
    {
      clipPath: "inset(0% 0 0% 0 round 0.25em)",
      scale: 1,
      duration: 1.5,
      ease: "power4.out",
      stagger: 0.15,
      scrollTrigger: {
        trigger: allMembers[0],
        start: "top 75%",
      },
    });

    const isTouch = window.matchMedia("(hover: none)").matches;

    allMembers.forEach((member) => {
      const names = member.querySelectorAll(".abt_team_member_name");
      const lines = Array.from(names).flatMap(n => n._split?.lines || []);
      const overlay = member.querySelector(".abt_team_main_member_overlay");
      const img = member.querySelector(".abt_team_main_member_photo");

      if (lines.length) gsap.set(lines, { yPercent: 120 });
      if (overlay) gsap.set(overlay, { autoAlpha: 0 });

      const activate = () => {
        allMembers.forEach((other) => {
          if (other !== member) {
            const otherOverlay = other.querySelector(".abt_team_main_member_overlay");
            if (otherOverlay) gsap.to(otherOverlay, {
              autoAlpha: 0.625,
              duration: 0.375
            });
          }
        });
        gsap.killTweensOf([lines, overlay]);
        gsap.to(lines, { yPercent: 0, duration: 0.75, ease: "power4.out", stagger: 0.125 });
        if (overlay) gsap.to(overlay, { autoAlpha: 0, duration: 0.375 });
        if (img) gsap.to(img, { scale: 1.05, duration: 0.6, ease: "power2.out" });
      };

      const deactivate = () => {
        allMembers.forEach((other) => {
          if (other !== member) {
            const otherOverlay = other.querySelector(".abt_team_main_member_overlay");
            if (otherOverlay) gsap.to(otherOverlay, { autoAlpha: 0, duration: 0.375 });
          }
        });
        gsap.killTweensOf([lines, overlay]);
        gsap.to(lines, {
          yPercent: 120,
          duration: 0.75,
          ease: "power4.out",
          stagger: 0.125
        });
        if (overlay) gsap.to(overlay, { autoAlpha: 0, duration: 0.375 });
        if (img) gsap.to(img, { scale: 1, duration: 0.6, ease: "power2.out" });
      };

      if (isTouch) {
        let active = false;
        member.addEventListener("click", () => {
          if (active) {
            deactivate();
            active = false;
          } else {
            allMembers.forEach(other => {
              if (other !== member) other._active && other.click();
            });
            activate();
            active = true;
          }
          member._active = active;
        });
      } else {
        member.addEventListener("pointerenter", activate);
        member.addEventListener("pointerleave", deactivate);
      }
    });
  }

  function initWorkMarquee(container) {
    const wrap = container.querySelector(".projects_list_cms_wrap");
    const list = container.querySelector(".projects_list_cms_list");
    if (!wrap || !list) return;
    const items = list.querySelectorAll(".projects_list_cms_item");
    if (!items.length) return;

    items.forEach((item) => list.appendChild(item.cloneNode(true)));

    list.querySelectorAll(".projects_list_cms_item").forEach((item) => {
      const img = item.querySelector(".projects_list_cms_item_image");
      if (!img) return;
      item.addEventListener("pointerenter", () => gsap.to(img, {
        scale: 1.05,
        duration: 0.4,
        ease: "power2.out"
      }));
      item.addEventListener("pointerleave", () => gsap.to(img, {
        scale: 1,
        duration: 0.4,
        ease: "power2.out"
      }));
    });

    const mm = gsap.matchMedia();

    mm.add(MM_DESKTOP, () => {
      let x = 0;
      const baseSpeed = -0.75;
      let speed = baseSpeed;
      let dragging = false;
      let prevProxyX = 0;
      let singleWidth = list.scrollWidth / 2;

      const tickerFn = () => {
        if (!dragging) speed += (baseSpeed - speed) * 0.05;
        x += speed;
        if (x <= -singleWidth) x += singleWidth;
        if (x > 0) x -= singleWidth;
        gsap.set(list, { x });
      };
      gsap.ticker.add(tickerFn);

      const proxy = document.createElement("div");
      document.body.appendChild(proxy);
      gsap.set(proxy, {
        x: 0,
        position: "fixed",
        top: -9999,
        left: -9999,
        width: 1,
        height: 1
      });

      const draggable = Draggable.create(proxy, {
        type: "x",
        inertia: true,
        maxDuration: 1,
        minDuration: 0.5,
        trigger: wrap,
        cursor: "grab",
        activeCursor: "grabbing",
        zIndexBoost: false,
        onDragStart() {
          dragging = true;
          prevProxyX = this.x;
        },
        onDrag() {
          speed = this.x - prevProxyX;
          prevProxyX = this.x;
        },
        onThrowUpdate() {
          speed = this.x - prevProxyX;
          prevProxyX = this.x;
        },
        onThrowComplete() {
          dragging = false;
          gsap.set(proxy, { x: 0 });
          prevProxyX = 0;
        },
      })[0];

      const ro = new ResizeObserver(() => { singleWidth = list.scrollWidth / 2; });
      ro.observe(wrap);

      return () => {
        gsap.ticker.remove(tickerFn);
        ro.disconnect();
        draggable.kill();
        proxy.remove();
        gsap.set(list, { x: 0 });
      };
    });

    return () => mm.revert();
  }

  function initProjectsLink(container) {
    const link = container.querySelector("[data-project-link]");
    if (!link) return;
    const img = link.querySelector("img");
    if (!img) return;

    const onEnter = () => gsap.to(img, { scale: 1.05, duration: 0.4, ease: "power2.out" });
    const onLeave = () => gsap.to(img, { scale: 1, duration: 0.4, ease: "power2.out" });

    link.addEventListener("pointerenter", onEnter);
    link.addEventListener("pointerleave", onLeave);
  }

  function initHome(container) {
    playHeroIntro(container);
    initHomeIntro(container);
    initHomeCover(container);
    const cleanupCursor = initHomeWork(container);
    const cleanupImgFollow = initHomeHero(container);
    initWorkImageHover(container);

    const svcWrap = container.querySelector(".svc_container");
    if (svcWrap) {
      gsap.set(svcWrap, { position: "relative", zIndex: 10 });
    }
    const cleanupSvcCover = svcWrap ? setupCoverSection(svcWrap, { watchResize: false }) : null;

    const workOverlay = container.querySelector(".work_overlay");
    if (workOverlay && svcWrap) {
      gsap.to(workOverlay, {
        autoAlpha: 1,
        ease: "none",
        scrollTrigger: {
          trigger: svcWrap,
          start: "top bottom",
          end: "top top",
          scrub: true,
          invalidateOnRefresh: true,
        }
      });
    }

    initHomeServices(container);
    initHomeAbout(container);

    const workMain = container.querySelector(".work_main_wrap");
    initScrollAnimations(container, workMain);

    return () => {
      cleanupSvcCover?.();
      cleanupCursor?.();
      cleanupImgFollow?.();
    };
  }

  function initWork(container) {
    playHeroIntro(container);
    const cleanupMarquee = initWorkMarquee(container);
    initScrollAnimations(container);

    return () => {
      cleanupMarquee?.();
    };
  }

  function initAbout(container) {
    playHeroIntro(container);
    initAboutDropdown(container);
    const cleanupCover = initAboutCover(container);
    const cleanupTeam = initAboutTeam(container);
    initScrollAnimations(container);

    return () => {
      cleanupCover?.();
      cleanupTeam?.();
    };
  }

  function initServices(container) {
    playHeroIntro(container);
    const cleanupMarquee = initServicesMarquee(container);
    initServicesSvc(container);
    const cleanupTestimonials = initServicesTestimonials(container);
    initServicesCover(container);
    const svcWrap = container.querySelector(".svc_svc_main_wrap");
    initScrollAnimations(container, svcWrap);

    return () => {
      cleanupMarquee?.();
      cleanupTestimonials?.();
    };
  }

  function initProject(container) {
    playHeroIntro(container);
    initProjectsLink(container);
    initScrollAnimations(container);
  }

  function init404(container) {
    playHeroIntro(container);
    initScrollAnimations(container);
  }

  const pages = {
    home: initHome,
    work: initWork,
    about: initAbout,
    services: initServices,
    project: initProject,
    "404": init404,
  };

  function cleanupPage(container = document.querySelector('[data-barba="container"]')) {
    if (typeof state.pageCleanup === "function") {
      state.pageCleanup();
      state.pageCleanup = null;
    }

    state.ctx?.revert();
    state.ctx = null;

    cleanupSplitText();

    if (container) {
      container.querySelectorAll("[data-text-split]").forEach((el) => {
        delete el._split;
      });
    }

    ScrollTrigger.getAll().forEach((t) => t.kill());
  }

  function initPageBase(container) {
    // await document.fonts.ready;
    state.ctx = gsap.context(() => {
      initCommon(container);
      prepHeroIntro(container);
    }, container);
  }

  function prepHeroIntro(container) {
    const hero = container.querySelector("[data-hero]");
    if (!hero) return;
    const namespace = container.dataset.barbaNamespace;
    const svgs = hero.querySelectorAll("[data-hero-svg]");
    const mdEl = hero.querySelector("[data-hero-text-md]");
    const cptEls = hero.querySelectorAll("[data-hero-cpt]");
    const texts = hero.querySelectorAll("[data-hero-text]");
    const imgs = hero.querySelectorAll("[data-hero-img]");
    const btn = hero.querySelector("[data-hero-btn]");
    const btnLines = hero.querySelectorAll(".link_btn_line");

    if (namespace === "home") {
      if (svgs.length) gsap.set(svgs, { yPercent: 120 });
      if (btnLines.length) gsap.set(btnLines, { clipPath: "inset(0 100% 0 0)" });
      imgs.forEach((img) => gsap.set(img, { scale: 0, transformOrigin: "center center" }));
      // EAD/LSM initial states
      var heroEad = hero.querySelector('#hero-ead');
      var heroLsm = hero.querySelector('#hero-lsm');
      if (heroEad) gsap.set(heroEad, { opacity: 0, x: -400, y: -200 });
      if (heroLsm) { heroLsm.textContent = ''; heroLsm.style.visibility = 'visible'; heroLsm.style.borderRight = '4px solid #FFFFFF'; heroLsm.style.paddingRight = '0.05em'; }
      if (btn) {
        const btnTexts = btn.querySelectorAll(".link_btn_text");
        const lines = Array.from(btnTexts).flatMap(t => t._split?.lines || []);
        if (lines.length) gsap.set(lines, { yPercent: 120 });
      }
    } else {
      if (svgs.length) gsap.set(svgs, { yPercent: 120 });
      if (namespace === "services") imgs.forEach((img) => gsap.set(
        img, { clipPath: "inset(100% 0 0 0)" }));
      if (namespace === "project") imgs.forEach((img) => gsap.set(
        img, { clipPath: "inset(0 0 100% 0)" }));
      if (namespace === "404" && btn) {
        const btnTexts = btn.querySelectorAll(".link_btn_text");
        const lines = Array.from(btnTexts).flatMap(t => t._split?.lines || []);
        const btnLines = btn.querySelectorAll(".link_btn_line");
        if (lines.length) gsap.set(lines, { yPercent: 120 });
        if (btnLines.length) gsap.set(btnLines, { clipPath: "inset(0 100% 0 0)" });
      }
    }

    if (mdEl?._split?.lines) gsap.set(mdEl._split.lines, { yPercent: 120 });
    cptEls.forEach((el) => {
      if (el?._split?.lines) gsap.set(el._split.lines, { autoAlpha: 0 });
    });
    texts.forEach((text) => gsap.set(text, { autoAlpha: 0, y: "0.5em" }));
  }

  function runPageIntro(container, namespace) {
    const pageInit = pages[namespace];
    if (!pageInit) return;

    state.ctx?.add(() => {
      const maybeCleanup = pageInit(container);
      if (typeof maybeCleanup === "function") state.pageCleanup = maybeCleanup;
    });
  }

  function resetWebflow(data) {
    const parser = new DOMParser();
    const dom = parser.parseFromString(data.next.html, "text/html");
    const wfPage = dom.querySelector("html")?.getAttribute("data-wf-page");
    if (wfPage) document.documentElement.setAttribute("data-wf-page", wfPage);

    window.Webflow?.destroy();
    window.Webflow?.ready();

    const ix2 = window.Webflow?.require?.("ix2");
    ix2?.init?.();
  }

  function transitionCover(currentContainer = null) {
    const screen = document.querySelector("#page-transition");
    if (!screen) return Promise.resolve();
    gsap.set(screen, { display: "block", yPercent: 100 });

    let overlay = null;
    if (currentContainer) {
      overlay = document.createElement("div");
      overlay.style.cssText =
        "position:fixed;inset:0;background:#000;opacity:0;pointer-events:none;z-index:98;";
      document.querySelector(".page_wrap").appendChild(overlay);
    }

    return new Promise((res) => {
      const tl = gsap.timeline({
        onComplete: () => {
          overlay?.remove();
          res();
        },
      });

      if (currentContainer) {
        tl.to(overlay, { opacity: 0.8, duration: 0.625, ease: "power2.inOut" }, 0);
      }

      tl.to(screen, { yPercent: 0, duration: 0.625, ease: "power2.inOut" }, 0);

      tl.add(() => window.__closeMobileMenu?.(), 0.625);
    });
  }

  function transitionReveal() {
    const screen = document.querySelector("#page-transition");
    if (!screen) return Promise.resolve();

    return new Promise((res) => {
      gsap.to(screen, {
        yPercent: -100,
        duration: 0.625,
        ease: "power2.inOut",
        onComplete: () => {
          gsap.set(screen, { display: "none" });
          res();
        },
      });
    });
  }

  function waitForFonts() {
    return document.fonts?.ready || Promise.resolve();
  }

  function runHomeLoader({ onComplete } = {}) {
    const loader = document.querySelector("#loader");
    if (!loader) { onComplete?.(); return Promise.resolve(); }
    if (loaderPlayed) {
      loader.setAttribute("aria-hidden", "true");
      onComplete?.();
      return Promise.resolve();
    }
    loaderPlayed = true;

    const logo = loader.querySelector("[data-loader-logo]");
    const logoTargets = logo ? getFlickerTargets(logo) : null;
    if (logo && logo.matches && logo.matches('img')) {
      // Force it to use the fade-in fallback instead of flicker array
      logoTargets.length = 0; 
    }
    const percentEl = loader.querySelector("[data-loader-percent]");
    const barFill = loader.querySelector("[data-loader-bar-fill]");

    gsap.set(loader, { display: "block", autoAlpha: 1 });
    if (logoTargets?.length) gsap.set(logoTargets, { autoAlpha: 0 });
    else if (logo) gsap.set(logo, { autoAlpha: 0 }); // Hide it instantly so it can fade in
    if (barFill) gsap.set(barFill, { clipPath: "inset(0 100% 0 0)" });

    const prog = { v: 0 };

    function setProgress(v) {
      const val = Math.round(v);
      if (percentEl) percentEl.textContent = `${val}%`;
      if (barFill) {
        const right = 100 - v;
        gsap.set(barFill, { clipPath: `inset(0 ${right}% 0 0)` });
      }
    }
    setProgress(0);
    scrollStop?.();

    const tl = gsap.timeline({
      delay: 0.2,
      onComplete: () => {
        gsap.set(loader, { display: "none" });
        scrollStart?.();
        onComplete?.();
      }
    });

    if (logoTargets?.length) tl.add(addFlickerReveal(logoTargets));
    else if (logo) tl.fromTo(logo, 
    { autoAlpha: 0, scale: 0.7, filter: "brightness(0) blur(12px)", rotation: -2 }, 
    { autoAlpha: 1, scale: 1.05, filter: "brightness(0) blur(0px)", rotation: 0, duration: 1.8, ease: "expo.out" });

    tl.to(prog, { v: 77, duration: 1.2, ease: "power2.out", onUpdate: () => setProgress(prog.v) },
      "<");
    tl.add(() => waitForFonts());
    tl.to(prog, {
      v: 100,
      duration: 0.675,
      ease: "power2.inOut",
      onUpdate: () => setProgress(prog
        .v)
    }, "<");
    tl.to({}, { duration: 0.15 });
    tl.to(loader, { delay: 1.5, autoAlpha: 0, duration: 0.35, ease: "power2.out" });

    return tl;
  }

  function applyNavState(namespace) {
    const nav = document.querySelector("[data-navbar]");
    if (!nav) return;

    const links = nav.querySelectorAll("[data-nav-link]");
    const isHome = namespace === "home";

    document.body.classList.toggle("is-home", isHome);

    links.forEach((a) => {
      a.classList.toggle("is-active", !isHome && a.dataset.navLink === namespace);
    });
  }

  function bindNavClickWithTransition() {
    const nav = document.querySelector("[data-navbar]");
    if (!nav) return;

    nav.addEventListener("click", (e) => {
      const a = e.target.closest("[data-nav-link]");
      if (!a) return;

      const currentNs =
        document.querySelector('[data-barba="container"]')?.dataset?.barbaNamespace;

      const nextNs = a.dataset.navLink;

      if (currentNs && nextNs === currentNs) {
        e.preventDefault();
        e.stopPropagation();
        const targetId = a.getAttribute('href');
        if (targetId && targetId.startsWith('#')) {
            const el = document.querySelector(targetId);
            if (el) el.scrollIntoView({ behavior: 'smooth' });
            else window.scrollTo({ top: 0, behavior: 'smooth' });
        } else {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        }
        return;
      }

      document.body.classList.remove("is-home");

      nav.querySelectorAll("[data-nav-link].is-active").forEach((l) => l.classList.remove(
        "is-active"));

      a.classList.add("is-active");
    }, true);
  }

  function initPageTransitions() {

    window.addEventListener('popstate', () => {
      scrollStop();
      const currentScroll = window.scrollY;
      requestAnimationFrame(() => {
        window.scrollTo(0, currentScroll);
      });
    });

    initLenis();
    initPersistentUI();
    bindNavClickWithTransition();

    applyNavState(
      document.querySelector('[data-barba="container"]')?.dataset?.barbaNamespace
    );

    barba.hooks.afterEnter((data) => {
      applyNavState(data.next.namespace);
    });

    barba.hooks.after(() => {
      requestAnimationFrame(() => {
        ScrollTrigger.refresh(true);
        scroll?.resize?.();
      });
    });

    let leavePromise = Promise.resolve();

    barba.init({
      sync: false,
      preventRunning: true,

      transitions: [
      {
        name: "default",

        async once(data) {
          setNavCurrent(data.next.namespace);
          const next = data.next.container;
          const namespace = data.next.namespace;

          const screen = document.querySelector("#page-transition");
          if (screen) gsap.set(screen, { display: "none", yPercent: 100 });

          await document.fonts.ready;

          initPageBase(next);
          document.documentElement.classList.remove('is-loading');

          window.scrollTo(0, 0);
          scrollResize();
          ScrollTrigger.refresh(true);

          runHomeLoader({
            onComplete: () => {
              runPageIntro(next, namespace);
            }
          });

          // runPageIntro(next, namespace);

          scrollStart();
        },

        async leave(data) {
          scrollStop();
          setNavTransitionMode(true);
          setNavCurrent(data.current.namespace);

          leavePromise = (async () => {
            await transitionCover(data.current.container);

            gsap.set(data.current.container, {
              autoAlpha: 0,
              pointerEvents: "none"
            });

            cleanupPage(data.current.container);

            data.current.container.remove();
          })();

          return leavePromise;
        },

        async beforeEnter(data) {
          resetWebflow(data);
        },

        async enter(data) {
          setNavCurrent(data.next.namespace);
          await leavePromise;
          await document.fonts.ready;
          const next = data.next.container;
          const namespace = data.next.namespace;

          gsap.set(next, { autoAlpha: 1 });

          initPageBase(next);

          window.scrollTo(0, 0);

          scrollResize();
          ScrollTrigger.refresh(true);

          const revealPromise = transitionReveal();

          setTimeout(() => {
            runPageIntro(next, namespace);
          }, 250);

          await revealPromise;

          scrollStart();
        },

        async after(data) {
          setNavTransitionMode(false);
        },
      }, ],
    });
  }

  initPageTransitions();

})();


